//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktivitet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aktivitet()
        {
            this.Anmälan = new HashSet<Anmälan>();
        }
    
        public int AktID { get; set; }
        public string Namn { get; set; }
        public System.DateTime Tillfälle { get; set; }
        public int AntalPlatser { get; set; }
    
        public virtual Anställd Anställd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anmälan> Anmälan { get; set; }
        public virtual Ämne Ämne { get; set; }
    }
}
