//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasModelContainer : DbContext
    {
        public DatabasModelContainer()
            : base("name=DatabasModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<UtbProgram> UtbProgram { get; set; }
        public virtual DbSet<Anmälan> Anmälan { get; set; }
        public virtual DbSet<Aktivitet> Aktivitet { get; set; }
        public virtual DbSet<Erbjudande> Erbjudande { get; set; }
        public virtual DbSet<Ämne> Ämne { get; set; }
    }
}
