//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Person
    {
        public string Förnamn { get; set; }
        public string Efternamn { get; set; }
        public long PersNr { get; set; }
        public string Adress { get; set; }
        public long PostNr { get; set; }
        public string Ort { get; set; }
        public string TelNr { get; set; }
        public string Email { get; set; }
        public string Lösenord { get; set; }
    }
}
